### PR TITLE
Add balena & balenaHub support

### PR DESCRIPTION
**Pull request by chrisys**
Hey there - cool project! I work at balena and wanted to try your container to see if it runs, which it does, beautifully. So, I added a docker-compose file and balena config that allows the app to be pushed to a balena device without requiring any further configuration - it includes a container with a browser to show the output on a screen and an FBCP container for running the small TFTs. This makes it possible to get up and running in a few minutes - zero command line stuff needed! I've tested this setup on a Pi3 and a Pi4.

In addition to powering the deploy button, the balena.yml and logo will also allow the project to be listed on https://hub.balena.io :)

### CODE REVIEW

**Comment by chrisys** [comment]
For reference, the docs for what I added are here: https://www.balena.io/docs/learn/deploy/deploy-with-balena-button/

**Comment by Ryandev** [comment]
Awesome work! Well done on getting Balena support! It makes deployment even easier now.

I'm happy to accept the new changes. However can you update the yml to point to the existing app icon under public/logo512.png & remove the /logo.png

**Comment by chrisys** [comment]
@Ryandev thanks for the feedback - changes made! I didn't notice you already had a much better logo than my attempt 😂

**Comment by Ryandev** [comment]
I'm no designer, but thanks! That's all merged in now 🙂

**Comment by chrisys** [comment]
Awesome, now listed on balenaHub too!

**Pull request merged**
